# Generated by Django 2.1.5 on 2019-01-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('non-binary', 'non-binary'), ('trans', 'transgender'), ('two-spirited', 'two-spirited'), ('male', 'male')], max_length=20)),
                ('race', models.CharField(choices=[('Black', 'African American'), ('Black', 'Black'), ('Latinx', 'Hispanic'), ('Latinx', 'Latino'), ('Latinx', 'Latinx'), ('White', 'European American'), ('White', 'Caucasian'), ('White', 'White'), ('Asian', 'Asian American'), ('Asian', 'Asian'), ('Indigenous', 'Native'), ('Indigenous', 'Native American'), ('Indigenous', 'Alaska Native'), ('Pacific Islander', 'Native Hawaiian'), ('Pacific Islander', 'Pacific Islander')], max_length=20)),
                ('orientation', models.CharField(choices=[('straight', 'straight'), ('queer', 'lesbian'), ('queer', 'gay'), ('queer', 'bisexual'), ('asexual', 'asexual')], max_length=20)),
                ('transplant', models.BooleanField(default=False)),
                ('location_city', models.CharField(max_length=20)),
                ('location_state', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'adie',
                'verbose_name_plural': 'adies',
                'ordering': ['race'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_size', models.CharField(choices=[('startup', 'startup company'), ('small', 'small company'), ('large', 'large company')], max_length=20)),
                ('org_size', models.IntegerField()),
                ('location_city', models.CharField(max_length=20)),
                ('location_state', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=128)),
                ('adies_present', models.BooleanField(default=False, null=True)),
                ('level_of_microaggressions', models.CharField(choices=[('NONE', 'one comment'), ('LOW', 'two comments'), ('MODERATE', 'comments and attitude'), ('HIGH', 'uncomfortable at the start')], max_length=20)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['level_of_microaggressions'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiations', models.BooleanField(default=False)),
                ('base_amount', models.IntegerField()),
                ('signing_bonus', models.IntegerField(null=True)),
                ('relocation_package', models.IntegerField(null=True)),
                ('health_insurance', models.IntegerField(null=True)),
                ('retirement', models.CharField(blank=True, default='', max_length=128)),
                ('vacation_days', models.IntegerField()),
                ('hire_type', models.CharField(choices=[('INTERNAL', 'internal'), ('EXTERNAL', 'external')], max_length=20)),
                ('stocks', models.IntegerField()),
                ('adie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adie_app.Adie')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adie_app.Company')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['adie_id'],
            },
        ),
    ]
