# Generated by Django 2.1.5 on 2019-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('startup', 'startup company'), ('small', 'small company'), ('large', 'large company')], max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='level_of_microaggressions',
            field=models.CharField(choices=[('NONE', 'one comment'), ('LOW', 'two comments'), ('MODERATE', 'comments and attitude'), ('HIGH', 'uncomfortable at the start')], max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='location_city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='location_state',
            field=models.CharField(max_length=120),
        ),
    ]
