# Generated by Django 2.1.5 on 2019-01-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adie_app', '0002_auto_20190108_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='level_of_microaggressions',
            field=models.CharField(choices=[('NONE', 'one comment'), ('LOW', 'two comments'), ('MODERATE', 'comments and attitude'), ('HIGH', 'uncomfortable at the start')], max_length=120, null=True),
        ),
    ]
